In [1]:
# Numpy: Efficient for performing mathematical operations as compared to python-lists.

In [2]:
# Example Code:
import numpy as np
import time

numbers = [1,2,3,4,5,6,7,8,9,10]*10000
start_time = time.time()
for number in range(len(numbers)):
    numbers[number] = numbers[number]*2
end_time = time.time()
print(f"Time taken for List: {end_time-start_time}")

Time taken for List: 0.039893388748168945


In [3]:
# Numpy array
numbers = [1,2,3,4,5,6,7,8,9,10]*10000
nums = np.array(numbers)
start_time = time.time()
for number in range(len(nums)):
    nums[number] = nums[number]*2
end_time = time.time()
print(f"Time taken for Numpy array: {end_time-start_time}")

Time taken for Numpy array: 0.09275174140930176


In [4]:
import sys
a = [1,2,3,4,5]
array = np.array(a)

print("List  size:",sys.getsizeof(a))  #Memory occupied by list 
print("Array size:",array.nbytes)      #Memory occupied by array

List  size: 104
Array size: 20


In [5]:
a = [1,'a',"apple",1.2]   #Numpy array allows only same type of data to be stored
arr = np.array(a)
print(arr) 

['1' 'a' 'apple' '1.2']


In [6]:
import numpy as np  # alias as np

In [7]:
zero_dimension_array = np.array(2)  #zero dimension array
one_dimension_array = np.array([1,2,3,4,5])   # []: One dimension
two_dimension_array = np.array([[1,2,3,4,5]])  #[[]] : Two diemsnion 
three_dimension_array = np.array([[[1,2,3,4,5]]])  #[[[]]] : Three diemsnion 
print(f"Dimension of array: {zero_dimension_array.ndim}")  
print(f"Dimension of array: {zero_dimension_array.ndim}")
print(f"Dimension of array: {two_dimension_array.ndim}")
print(f"Dimension of array: {three_dimension_array.ndim}")

Dimension of array: 0
Dimension of array: 0
Dimension of array: 2
Dimension of array: 3


In [8]:
elements = np.arange(1,11)  # (start,stop,steps): start = inclusive , stop = exlusive.
elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.linspace(0,1,5)  # linspace(start,stop,number_of_values): creates evenly distributed values between start & stop
print("Evenly space numbers:",arr)

Evenly space numbers: [0.   0.25 0.5  0.75 1.  ]


In [10]:
logs = np.logspace(1,3,3) #logspace(start,stop,number_of_points): start = 10¹ , end = 10³ : no_of_points = 3
print(logs)

[  10.  100. 1000.]


In [11]:
zeros_1d = np.zeros(5,int)      #array full of zeros having 1-Dimension
zeros_2d = np.zeros((2,4),int)  #array full of zeros having 2-Dimensions.
zeros_random_dimensions = np.zeros((2,3,4,5,6),int)
print(f"1-D zeros array:\n{zeros_1d}")
print(f"2-D zeros array:\n{zeros_2d}")
print(f"R-D zeros array:\n{zeros_random_dimensions}")

1-D zeros array:
[0 0 0 0 0]
2-D zeros array:
[[0 0 0 0]
 [0 0 0 0]]
R-D zeros array:
[[[[[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]]


  [[[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]]


  [[[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]]

   [[0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0 0 0 0]
    [0 0 0

In [12]:
ones_1d = np.ones(2,int)      #array full of ones having 1-Dimension
ones_3d = np.ones((3,3),int)  #array full of ones having 3-Dimensions
print(f"1-D ones array\n{ones_1d}")
print(f"2-D ones array\n{ones_3d}")

1-D ones array
[1 1]
2-D ones array
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
full_1d = np.full(10,3)    #full(elements,default_value): createes array full of 1-D having our choosen value
full_2d = np.full([2,2],4) #full(elements,default_value): createes array full of 2-D having our choosen value

print(f"1-D Full array:\n{full_1d}")
print(f"2-D full array:\n{full_2d}")

1-D Full array:
[3 3 3 3 3 3 3 3 3 3]
2-D full array:
[[4 4]
 [4 4]]


In [14]:
uninitialized_array = np.empty([2,3])  #uninitialized array : faster and used for overriding values in future usages.
print(f"Uninitialized array:\n{uninitialized_array}")

Uninitialized array:
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.33511290e-306 6.23058368e-307 2.22526399e-307]]


In [15]:
random_uniform_floats_1d = np.random.rand(10)   #generates random uniformly-distributed floating values between 0-1 of 1-D
random_uniform_floats_2d = np.random.rand(2,3)  #generates random uniformly-distributed floating values between 0-1 of 2-D
print(f"1-D random uniform distributed floats:\n{random_uniform_floats_1d}")
print(f"2-D random uniform distributed floats:\n{random_uniform_floats_2d}")

1-D random uniform distributed floats:
[0.09855168 0.45081092 0.899945   0.33252248 0.50073496 0.99524789
 0.33217222 0.71536612 0.78315176 0.21388364]
2-D random uniform distributed floats:
[[0.80413103 0.83364654 0.71305313]
 [0.25114783 0.21088146 0.3035528 ]]


In [16]:
random_normal_floats_1d = np.random.randn()    #generates random normal-dstributed floating values having mean = 0 & std = 1 of 1-D
random_normal_floats_2d = np.random.randn(2,3) #generates random normal-dstributed floating values having mean = 0 & std = 1 of 2-D
print(f"1-D random normal distributed floats:\n{random_normal_floats_1d}")
print(f"2-D random normal distributed floats:\n{random_normal_floats_2d}")

1-D random normal distributed floats:
0.4028192031414143
2-D random normal distributed floats:
[[-1.28216919  0.60405091 -0.9810478 ]
 [-3.3153687   1.72761037  0.59182689]]


In [17]:
random_number = np.random.randint(10,100)               #any 1-random integer between 10 and 100
random_numbers = np.random.randint(10,100,size=(5,10))  #multiple-random integers  between 10 and 100 (5*10)=50 elements
print(f"Random number:\n{random_number}")
print(f"Random numbers :\n{random_numbers}")

Random number:
88
Random numbers :
[[70 21 98 62 44 32 50 58 60 31]
 [98 80 74 31 78 84 27 54 94 56]
 [89 58 65 11 43 57 40 15 60 42]
 [25 68 17 60 90 11 65 38 14 80]
 [38 24 52 87 46 69 83 88 89 71]]


## Numpy Data Types
* i for integer
* b for boolean
* u for unsigned integer
* f for float
* c for complex float
* m for timedelta
* M for datetime
* O for Object
* S for Strings
* U for unicode string
* V for memory
##### Note: Use dtype function to check the type of each structure

In [18]:
numbers_array = np.array([1,2,3,4,5,6])
print(f"Array values: {numbers_array}")
print(f"Array type: {numbers_array.dtype}")

Array values: [1 2 3 4 5 6]
Array type: int32


In [19]:
my_list = ["string",1,2,5.6]
list_array = np.array(my_list)
print(f"List Array values: {list_array}")
print(f"List Array type: {list_array.dtype}")

List Array values: ['string' '1' '2' '5.6']
List Array type: <U32


In [20]:
integer_array = np.array([1,2,3,4,5.4],dtype=float)     #assigning customized datatype to the array elements
float_array = np.array([1.2,2.2,3.3,4.4,5.5],dtype=int) #assigning customized datatype to the array elements
print(f"dtype of integer_array: {integer_array.dtype}")
print(f"dtype of float_array: {float_array.dtype}")

dtype of integer_array: float64
dtype of float_array: int32


### Type Casting: Converting elements from datatype to another datatype using astype() function

In [21]:
int_array = np.array([1,2,3,4,5])
new_float_array = int_array.astype(float)
print(f"Array values: {new_float_array}")
print(f"Array data type: {new_float_array.dtype}")

floating_array = np.array([1.2,3.4,4.4,5.5])
new_int_array = floating_array.astype(int)
print(f"Array values: {new_int_array}")
print(f"Array data type: {new_int_array.dtype}")

Array values: [1. 2. 3. 4. 5.]
Array data type: float64
Array values: [1 3 4 5]
Array data type: int32


#### Type Casting Errors

In [22]:
string_array = np.array(["1","2","3"])  #Converting string numbers into integer values
in_array_1 = string_array.astype(int)
print("Converted array:",in_array_1)

# string_array = np.array(["1","2","3","hello"]) #Converting string numbers and literal into integer values (Error)
# in_array_2 = string_array.astype(int)
# print("Converted array:",in_array_2)

Converted array: [1 2 3]


#### Multi-dimensional arrays using np.array function

In [23]:
# multi_array = np.array([1,2,3],
#                       [2,4,5])   #shows an error: We can only pass one list to the np.array() function

multi_array = np.array([[1,2,3],
                        [4,5,6]])    #Works well: Now it is considered as a one list
print(f"Multi-array values:\n{multi_array}")
print(f"Multi-array shape: {multi_array.shape} = (rows,columns)")
print(f"Multi-array size: {multi_array.size}")
print(f"Multi-array dimension: {multi_array.dtype}")
print(f"Size of each item/element in an array: {multi_array.itemsize} bytes")

Multi-array values:
[[1 2 3]
 [4 5 6]]
Multi-array shape: (2, 3) = (rows,columns)
Multi-array size: 6
Multi-array dimension: int32
Size of each item/element in an array: 4 bytes


### Reshaping arrays using: Reshape, Ravel, Flatten
##### Note: Ravel : Returns view of original array ,  Flatten : Returns copy of original array

In [24]:
array_1d = np.array([1,2,3,4,5,6])   
reshaped_array = array_1d.reshape(3,2) 
new_reshaped_array = reshaped_array.reshape(1,6)  #Converting into same but shape of array will be changed form 1-D -> 2-D
print("_______ Reshaped function ________")
print(f"Original array:\n{array_1d}")  #1-Dimension array of rows =1, columns=6
print(f"Reshaped array:\n{reshaped_array}") #2-Dimension array of rows = 3, columns=2 
print(f"New Reshaped array:\n{new_reshaped_array}") #2-Dimesion array of rows = 1, columns=6 
print(f"Dimension: {array_1d.ndim}")
print(f"Dimension: {reshaped_array.ndim}")
print(f"Dimension: {new_reshaped_array.ndim}\n")

# ravel(): Converts any type of array into 1-D array (Returns: View)
print("_______ Ravel function ________")
ravel_array_1 = reshaped_array.ravel()
ravel_array_2 = new_reshaped_array.ravel()

print(f"Ravel array-1: {ravel_array_1}")
print(f"Ravel array-2: {ravel_array_2}")
print(f"Dimension: {ravel_array_1.ndim}")
print(f"Dimension: {ravel_array_2.ndim}")
ravel_array_1[0] = 1000  #Modifying 1 with 1000 value and then checking both the arrays (Changes reflected in original array)
print(f"Originla array:\n{reshaped_array}")
print(f"Ravel array:\n{ravel_array_1}\n")

# flatten(): Converts any type of array into 1-D array (Returns: Copy)
print("_______ Flatten function ________")
flatten_array_1 = reshaped_array.flatten()
flatten_array_2 = new_reshaped_array.flatten()
print(f"Flatten array-1: {flatten_array_1}")
print(f"Flatten array-2: {flatten_array_2}")
print(f"Dimension: {flatten_array_1.ndim}")
print(f"Dimension: {flatten_array_2.ndim}")
flatten_array_1[0] = 2000 #Modifying 1 with 2000 value and then checking both the arrays (Changes don't reflected in original array)
print(f"Originla array:\n{reshaped_array}")
print(f"Flatten array:\n{flatten_array_1}")

_______ Reshaped function ________
Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]
New Reshaped array:
[[1 2 3 4 5 6]]
Dimension: 1
Dimension: 2
Dimension: 2

_______ Ravel function ________
Ravel array-1: [1 2 3 4 5 6]
Ravel array-2: [1 2 3 4 5 6]
Dimension: 1
Dimension: 1
Originla array:
[[1000    2]
 [   3    4]
 [   5    6]]
Ravel array:
[1000    2    3    4    5    6]

_______ Flatten function ________
Flatten array-1: [1000    2    3    4    5    6]
Flatten array-2: [1000    2    3    4    5    6]
Dimension: 1
Dimension: 1
Originla array:
[[1000    2]
 [   3    4]
 [   5    6]]
Flatten array:
[2000    2    3    4    5    6]


## Arithmetic Operations

In [25]:
A = np.array([1,2,3])
B = np.array([4,5,2])

addition = A+B         #addition
subtraction = A-B      #subtraction
product = A*B          #product
division = A/B         #division
floor_division = A//B  #floor-division
remainder = A%B        #remainder
exponent = A**B        #exponent

print(f"Original arrays: {A} and {B}")
print(f"Addition: {addition}")
print(f"Subtraction: {subtraction}")
print(f"Product: {product}")
print(f"Division: {division}")
print(f"Integer division: {floor_division}")
print(f"Remainder: {remainder}")
print(f"Exponent: {exponent}")

Original arrays: [1 2 3] and [4 5 2]
Addition: [5 7 5]
Subtraction: [-3 -3  1]
Product: [ 4 10  6]
Division: [0.25 0.4  1.5 ]
Integer division: [0 0 1]
Remainder: [1 2 1]
Exponent: [ 1 32  9]


### Universal Functions : Built-in Math Functions

In [26]:
new_arr = np.array([1,4,9,16])
square_root = np.sqrt(new_arr)
exponential = np.exp([1,2])   #e¹ and e²
angles = [0,np.pi, np.pi/2]
sin_function = np.sin(angles)

print(f"Original array: {new_arr}")
print(f"Square root: {square_root}")
print(f"Result of e¹ and e²: {exponential}")
print(f"Sin of angles {angles} are: {sin_function}") #sin(π) = 1.2246468e-16 ⩰ 0

Original array: [ 1  4  9 16]
Square root: [1. 2. 3. 4.]
Result of e¹ and e²: [2.71828183 7.3890561 ]
Sin of angles [0, 3.141592653589793, 1.5707963267948966] are: [0.0000000e+00 1.2246468e-16 1.0000000e+00]


## Indexing and Slicing

In [27]:
nums_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Orignal array: {nums_array}\n")
 
print("_________ Indexing _________")
print(f"Value at first index: {nums_array[0]}")   #first element (indexing)
print(f"Value at last  index: {nums_array[-1]}\n")  #last element  (indexing)
print("_________ Slicing _________")
print(f"First 4 values: {nums_array[0:4]}")      #first 4 elements (slicing)
print(f"Last  4 values: {nums_array[-1:-5:-1]}") #last  4 elements (negative-slicing)
print(f"Reversed array values: {nums_array[::-1]}")
print(f"Every second element: {nums_array[::2]}")

odds = nums_array[::2]
evens = nums_array[1::2]
print(f"Odd elements:{odds}")
print(f"Even elements:{evens}")


matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(f"1st and 2nd row elements:\n{matrix[0:2,:]}")   #matrix[rows_slicing,columns_slicing]
print(f"2nd Column elements:\n{matrix[0:3,1:2]}")
print(f"Part of 2nd and 3rd rows:\n{matrix[1:,1:]}")

# Advanced indexing
indices = [0,2,3]
print(f"Taking elements from particular indices using take funciton:{np.take(matrix,indices)}")

# Iterating with nditer (Looping through arrays regardless of it's shape)
arr_2d = np.array([[1,2],[3,4]])
print("Elements in 2-d Array:",end=" ")
for element in np.nditer(arr_2d):
    print(element,end=" ")

# Iterating with ndenumerate (Looping through arrays accessing both element and indices)
for index,element in np.ndenumerate(arr_2d):
    print(f"Position: {index}, Value: {element}")

Orignal array: [ 1  2  3  4  5  6  7  8  9 10]

_________ Indexing _________
Value at first index: 1
Value at last  index: 10

_________ Slicing _________
First 4 values: [1 2 3 4]
Last  4 values: [10  9  8  7]
Reversed array values: [10  9  8  7  6  5  4  3  2  1]
Every second element: [1 3 5 7 9]
Odd elements:[1 3 5 7 9]
Even elements:[ 2  4  6  8 10]
1st and 2nd row elements:
[[1 2 3]
 [4 5 6]]
2nd Column elements:
[[2]
 [5]
 [8]]
Part of 2nd and 3rd rows:
[[5 6]
 [8 9]]
Taking elements from particular indices using take funciton:[1 3 4]
Elements in 2-d Array: 1 2 3 4 Position: (0, 0), Value: 1
Position: (0, 1), Value: 2
Position: (1, 0), Value: 3
Position: (1, 1), Value: 4


## Copy VS View

In [28]:
values = np.array([1,2,3,4,5])
view = values[1:3]  #creating view of 2nd and 3rd element
print(f"Original array: {values}")
print(f"View of an array: {view}")
print("________ Modifying view ________")
view[0] = 100  #changing the first element of a view
print(f"Original array:{values}") #changed
print(f"View after modifications: {view}\n")

copy = values[1:3].copy()
print(f"Original array: {values}")
print(f"Copy of an array: {copy}")
print("________ Modifying copy ________")
copy[0] = 200 #changing the first element of a copy
print(f"Original array:{values}")  #doesn't changed
print(f"Copy after modifications: {copy}")

Original array: [1 2 3 4 5]
View of an array: [2 3]
________ Modifying view ________
Original array:[  1 100   3   4   5]
View after modifications: [100   3]

Original array: [  1 100   3   4   5]
Copy of an array: [100   3]
________ Modifying copy ________
Original array:[  1 100   3   4   5]
Copy after modifications: [200   3]


### Transpose & Swapaxes

In [31]:
matrix_2 = np.array([[1,2,3],
                     [4,5,6]])
transposed_matrix = np.transpose(matrix_2)

print(f"Original matrix\n{matrix_2}")
print(f"Transpose of matrix\n{transposed_matrix}")

print(f"Shape of Original matrix: {matrix_2.shape}")
print(f"Shape of Transposed matrix: {transposed_matrix.shape}")

my_arr = np.array([[[1,2],[3,4]]])
shape1 = my_arr.shape
print(f"Shape of original array: {shape1}")
swap = np.swapaxes(my_arr,0,1)
shape2 = swap.shape  #shape after swapping axes
print(f"Shape after swapping axes: {shape2}")

Original matrix
[[1 2 3]
 [4 5 6]]
Transpose of matrix
[[1 4]
 [2 5]
 [3 6]]
Shape of Original matrix: (2, 3)
Shape of Transposed matrix: (3, 2)
Shape of original array: (1, 2, 2)
Shape after swapping axes: (2, 1, 2)


### Stacking & Splitting

In [58]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])

print(f"Original array-1: {ar1}")
print(f"Original array-2: {ar2}")

combined_array = np.concatenate((ar1,ar2))
print(f"Combined array\n{combined_array}")

#Vertical Stacking: vstack
vertical_stack = np.vstack((ar1,ar2))
print(f"Vertical stacked array\n{vertical_stack}")

#Horizontal Stacking: hstack  (array1 --> <--- array2)
horizontal_stack = np.hstack((ar1,ar2))
print(f"Horizontal stacked array\n{horizontal_stack}")

#Stack based on the axis
# Axis = 0 : Row wise stacking (vertically)
# Axis = 1 : Column wise stacking (horizontally)
row_wise_stacked = np.stack((ar1,ar2),axis=0)
print(f"Row wise stacking:\n{row_wise_stacked}")
column_wise_stacked = np.stack((ar1,ar2),axis=1)
print(f"Column wise stacking:\n{column_wise_stacked}")


print(f"Original array:\n{ar1}")
splitted_array = np.split(ar1,2)  #split(array_name,no_of_splits) : no_of_splits = satisfies equal division rule
print(f"Splitted array:\n{splitted_array}")

# Repeating array 
print(f"Original array:\n{ar1}")
repeated_array = np.repeat(ar1,2)
print(f"Repeated array: {repeated_array}")  #each element of array is repeated twice

# Tile
print(f"Original array:\n{ar1}")
tile_array = np.tile(ar1,2)
print(f"Tile array:\n{tile_array}")   #repeats array itself twice time (Not the elmeents)

Original array-1: [[1 2]
 [3 4]]
Original array-2: [[5 6]
 [7 8]]
Combined array
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Vertical stacked array
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacked array
[[1 2 5 6]
 [3 4 7 8]]
Row wise stacking:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Column wise stacking:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Original array:
[[1 2]
 [3 4]]
Splitted array:
[array([[1, 2]]), array([[3, 4]])]
Original array:
[[1 2]
 [3 4]]
Repeated array: [1 1 2 2 3 3 4 4]
Original array:
[[1 2]
 [3 4]]
Tile array:
[[1 2 1 2]
 [3 4 3 4]]


### Aggregate Functions

In [66]:
my_nums = np.array([1,2,3,4,5,6,7,8,9,10])

sum_of_elements = np.sum(my_nums)
average_of_elements = np.average(my_nums)
median = np.median(my_nums)
standard_deviation = np.std(my_nums)  #standard_deviation: How spread our data is
variance = np.var(my_nums)   #Variance = (standard_deviation)²
maximum_value = np.max(my_nums)
minimum_value = np.min(my_nums)

print(f"Sum of elements: {sum_of_elements}")
print(f"Average of elements: {average_of_elements}")
print(f"Median: {median}")
print(f"Standard Deviation: {standard_deviation}")
print(f"Variance: {variance}")
print(f"Maximum value: {maximum_value}")
print(f"Minimum value: {minimum_value}")

Sum of elements: 55
Average of elements: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Maximum value: 10
Minimum value: 1


### Axis Based Operations

In [73]:
matrix_A = [[1,2,3],
            [4,5,6],
            [7,8,9]]
sum_of_columns = np.sum(matrix_A,axis=1)
print(f"Sum of all columns: {sum_of_columns}")

sum_of_rows = np.sum(matrix_A, axis=0)
print(f"Sum of all rows: {sum_of_rows}")

cumulative_sum = np.cumsum(matrix_A)      #cumulative sum: Sn = x₁+x₂+x₃+x₄+...xn
print(f"Cumulative sum: {cumulative_sum}")  

cumulative_product = np.cumprod(matrix_A) #cumulative product: Pn = x₁*x₂*x₃*x₄*...xn
print(f"Cumulative product: {cumulative_product}")

Sum of all columns: [ 6 15 24]
Sum of all rows: [12 15 18]
Cumulative sum: [ 1  3  6 10 15 21 28 36 45]
Cumulative product: [     1      2      6     24    120    720   5040  40320 362880]


### Condition Based Choices

In [97]:
new_array = np.array([1,2,3,4,5,6,7,8,9,10])
result = np.where(new_array<3,"low","high")
indices = np.argwhere(new_array>2)
print(f"Result is: {result}")
# argwhere: row-column positions for 2d arrays
print(f"Indices:\n{indices}")

mask = np.logical_and(new_array>3, new_array<7)
print(f"Mask of values between 3 - 7 are: {mask}")
print(f"Values between 3 - 7 in array are: {new_array[mask]}")

Result is: ['low' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high']
Indices:
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Mask of values between 3 - 7 are: [False False False  True  True  True False False False False]
Values between 3 - 7 in array are: [4 5 6]
